---
output: pdf_document
title: "Report for Spotify"
author: Liam Andrew Beattie
---

# Purpose

Purpose of this work folder.

Ideally store a minimum working example data set in data folder.

Add binary files in bin, and closed R functions in code. Human Readable settings files (e.g. csv) should be placed in settings/


```{r,include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
rm(list = ls()) # Clean your environment:
gc() # garbage collection - It can be useful to call gc after a large object has been removed, as this may prompt R to return memory to the operating system.
library(tidyverse)
list.files('code/', full.names = T, recursive = T) %>% .[grepl('.R', .)] %>% as.list() %>% walk(~source(.))
import_multiple_rds("data/Coldplay_vs_Metallica") #brings additonal databases in
```


```{r data wrangling and filtering,include=FALSE}
data<-import_multiple_csv_and_join_identifier("data/Coldplay_vs_Metallica") %>% 
    merge_na_coloumns("duration","duration_ms") %>% 
    merge_na_coloumns("album_name","album") %>% 
    remove_rows_containing("name",c("live","Live","demo","Demo")) %>% 
    remove_rows_containing("album_name",c("live","Live","Deluxe","deluxe"))
```

```{r datawrangling,fig.cap="Song Popularity by Album for Coldplay and Metallica"}
data %>% violin_graph_music()

```



```{r timetrend Blur danceability , fig.cap="Time trend of danceability for Blur and similar artists "}
Broader_Spotify_Info %>%  plot_time_trend_of_similar_artist("Blur","danceability")

```

speechiness <dbl>, acousticness <dbl>, instrumentalness <dbl>, liveness <dbl>, valence <dbl>, tempo,
duration_ms danceability energy   key loudness
```{r timetrend coldplay tempo , fig.cap="Time trend of tempo for Coldplay and similar artists "}
Broader_Spotify_Info %>%  plot_time_trend_of_similar_artist("Coldplay","tempo")

```

```{r timetrend Green Day acousticness , fig.cap="Time trend of acousticness for Green Day and similar artists "}
Broader_Spotify_Info %>%  plot_time_trend_of_similar_artist("Green Day","acousticness")

```

```{r timetrend The Smashing Pumpkins loudness , fig.cap="Time trend of loudness for The Smashing Pumpkins and similar artists "}
Broader_Spotify_Info %>%  plot_time_trend_of_similar_artist("The Smashing Pumpkins","loudness")

```